baseURL = "https://ideacrew.com/"
languageCode = "en-us"
title = "IdeaCrew"
publishDir = "../public"

disableKinds = ["taxonomy", "term"]
pluralizelisttitles = false

# [menu]
#   [[menu.main]]
#     identifier = "about"
#     name = "The about section"
#     title = "about section"
#     url = "/about/"
#     weight = -1

