---
new_page_extension: md
auto_deploy: false
admin_path: "/hugo/static/admin"
webhook_url: 
sections:
- type: directory
  path: hugo/content/careers
  label: Careers
  create: documents
  match: "**/*"
  templates:
  - job
- type: directory
  path: hugo/content/work
  label: Work
  create: documents
  match: "**/*"
  templates:
  - quote
  - work
- type: document
  path: hugo/data/team.json
  label: Team
- type: document
  path: hugo/data/clients.json
  label: Clients
- type: directory
  path: hugo/content
  label: Pages
  create: all
  match: "*"
upload_dir: hugo/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.78.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: cd hugo && hugo server -D -E -F --port 8080 --bind 0.0.0.0
    --renderToDisk -d public
version: 0.71.1
